// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP2Qu9uUzzB29U1An7JG7nk3lUzYp8SUk',
    appId: '1:377847612438:web:02dbbc6f2c827729f92137',
    messagingSenderId: '377847612438',
    projectId: 'e-commerce-food-project',
    authDomain: 'e-commerce-food-project.firebaseapp.com',
    storageBucket: 'e-commerce-food-project.appspot.com',
    measurementId: 'G-8CF1S9KKZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhnjok4O4y2pZpJoK88tJy_MLUeaOvDBI',
    appId: '1:377847612438:android:d21ff8958e7e155af92137',
    messagingSenderId: '377847612438',
    projectId: 'e-commerce-food-project',
    storageBucket: 'e-commerce-food-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbB8n1LH9huRgx3E6JeL9KqhwyiZ0iSS0',
    appId: '1:377847612438:ios:184174c449686c16f92137',
    messagingSenderId: '377847612438',
    projectId: 'e-commerce-food-project',
    storageBucket: 'e-commerce-food-project.appspot.com',
    iosClientId: '377847612438-ats8a5r2v29d5ckfl8386emlnsq8luko.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCleanCodeEcommApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbB8n1LH9huRgx3E6JeL9KqhwyiZ0iSS0',
    appId: '1:377847612438:ios:184174c449686c16f92137',
    messagingSenderId: '377847612438',
    projectId: 'e-commerce-food-project',
    storageBucket: 'e-commerce-food-project.appspot.com',
    iosClientId: '377847612438-ats8a5r2v29d5ckfl8386emlnsq8luko.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCleanCodeEcommApp',
  );
}
